### ISSUE TITLE
Continuous integration and automated testing

### ISSUE THREAD

**Issue by adborden** [ckan/ckanext-report#22]
Would you consider adding automated tests and running those tests in a conintuous integration environment like [Travis CI](https://travis-ci.org/) or [CircleCI](https://circleci.com/)? This would help catch regressions in different versions of CKAN and Python.

**Comment by Zharktas** [comment]
Part on the python3 migration in #19, there are preliminary tests and travis integration, which needs to be updated to github actions. But I haven't had time to finish it.

**Comment by Zharktas** [comment]
Now there are GH actions and some tests :)
